# Generated by Django 4.2.7 on 2026-03-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_explanation',
            field=models.TextField(blank=True),
        ),
    ]
